### ISSUE TITLE
RLS or VSCode Rust plugin integration

### ISSUE THREAD

**Issue by nrc** [serayuzgur/crates#25]
Hi, this is really nice work! It's something we often get requests for in the RLS. Would you be interested in integrating this either with the Rust VSCode plugin or with the RLS itself? RLS integration would be better since it would make the features available with other editors (Atom, Eclipse, etc), however, I imagine it would be a bit more work to port this to working on the language server.

**Comment by serayuzgur** [comment]
Hi @nrc 
Thanks for your compliments. **Yes** , I did it for the community and it is great to hear that now there is an opportunity to reach more people.  

I think we should first integrate it with the plugin and then we can start to work on RLS. This will give us some time and we will see how community will respond. Also plugin may support 2 different configuration like with/without rls. Since RLS is not a must, having an ability to parse in plugin is a plus.

What do you think?

**Comment by nrc** [comment]
> I think we should first integrate it with the plugin and then we can start to work on RLS. 

This sounds like a good plan to me! Are you able to make a PR to https://github.com/rust-lang-nursery/rls-vscode ? Anything I can do to help?

**Comment by serayuzgur** [comment]
I am planning to publish crates to npm and add as a dependency to rls-vscode. Is it ok for you ? This way, I can continue to maintain crates  also rls-vscode will be easier to maintain.  I will add more features to crates and if you want to include these you will just increase the version of the dependency.

**Comment by nrc** [comment]
> Is it ok for you?

Yep, sounds great!

**Comment by softprops** [comment]
This is great news. It's confusing for users to have multiple rust extensions. Unifying these will be a much better out of the box experience

**Comment by serayuzgur** [comment]
Sorry for the long wait  but for now I decided not to work on this. I got my reasons and they are always open for discussion. Feel free to contact.
Thanks anyway.
