### ISSUE TITLE
Certain version numbers cause fetch errors.

### ISSUE THREAD

**Issue by zutils** [serayuzgur/crates#37]
In a cargo.toml file, there is a dependency:
 ipfs-api = "0.5.0-alpha2"

VSCode continuously gives the error "Fetch Errors: ipfs-api" ONLY on this crate. I suspect it has something to do with the "-alpha2" extension. There are other crates that may have a "-alpha"-like extension as well and it would be nice if it were handled.

**Comment by serayuzgur** [comment]
Hi @zutils thanks for the issue. I should check and debug it. I got no time for now so any PR's will welcome otherwise it will take some time.

**Comment by uHOOCCOOHu** [comment]
I also met this issue for crate `runtime`.

After digging the code, I found that it will produce "Fetch Errors" when no versions available. **It can be reached when `listPreReleases` is off but the crate has all preview versions.** [Related line](https://github.com/serayuzgur/crates/blob/e6f9fce54bffb8cbb04edc74d4b8544f906a338f/src/toml/listener.ts#L65)

I'm glad to fix it. But I'm questioning about what is expected in this case. Should it simply ignore the flag to display all preview versions (when nothing else available)?

BTW: `ipfs-api` works well *now*, because a non-preview version "0.5.1" has published.
