### ISSUE TITLE
Search crates.io

### ISSUE THREAD

**Issue by Weasy666** [serayuzgur/crates#69]
Would you consider adding a functionality like [Search crates.io](https://github.com/belfz/search-crates-io) had? With that you could search for crates and directly add them to you toml file from the autocompletion dropdown.
Seems like the original author does not maintain it anymore, but it is under MIT license and i think it would be great to integrate that into this extension.

**Comment by serayuzgur** [comment]
@Weasy666  thanks for your idea. Actually I was planning about it but than more important issues opened and this is delayed. During this time I always wrote my toml like 
`serde = ""`
by adding all dependencies with empty versions and than hovered it or used the command to fill all. 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/4561330/69214719-bc382a80-0b78-11ea-9d4b-fb67bd43f014.png">

or 

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/4561330/69214748-cb1edd00-0b78-11ea-81f1-05f0aaaa83fa.png">

If you still think support on typing is necessary  lets talk about use cases. 
One last think, please do not mind the `search crates.io` or its license. If we decide I prefer to code from scratch.

**Comment by Weasy666** [comment]
Your suggestion with typing `serde = ""` works, but that is not what i mean with searching crates.io. The feature i suggest is more or less emulating the search bar of crates.io so that you can search for crates you don't know by entering a keyword and choose one from the dropdown list that then gets automatically added to the toml file without the need to visit crates.io in a browser.
![suggestions](https://github.com/belfz/search-crates-io/blob/master/images/suggestions.gif)

**Comment by serayuzgur** [comment]
@Weasy666 you are right. For now we are restricted by the crates.io and github for request rate limits , so i think we need our own index server in order to implement this search also.

**Comment by LucianoBestia** [comment]
I think that "searching" for a crate is more than simply choosing one from the auto-completion drop-down. It is an important step and you want to avoid problems here. Making it too easy is missleading, I think.
I would rather have a handy fast accessible link to open the search on crates.io and lib.rs.
There is much to read about a crate than only a crate name, version and description.
I imagine this workflow:
- in cargo.toml I would try to write the name of the crate, but I don't remember it exactly:
` reader_for = ""`
Move the cursor on `""` and `vscode extension crates` shows.
There is no Available versions, because this name is not a crate.
But it has new commands:
![image](https://user-images.githubusercontent.com/31509965/83387439-60ddd380-a40a-11ea-940f-7713893d804d.png)
The first link simply opens <https://crates.io/search?q=reader_for>
The second link simply opens <https://lib.rs/search?q=reader_for>
I find the crate I want `reader_for_microxml`, read about it and manually copy/paste the name to cargo.toml.

Now I have the correct name and version `reader_for_microxml = "1.1.7"`.
If I go on the version number the extension opens like this:
![image](https://user-images.githubusercontent.com/31509965/83387694-cb8f0f00-a40a-11ea-8d93-7f1566ea7eaa.png)
I can:
1. open the crate.io page
<https://crates.io/crates/reader_for_microxml>
2. open the lib.rs
<https://lib.rs/crates/reader_for_microxml>
3. open cargo-crev reviews (still beta)
<https://bestia.dev/cargo_crev_web/crate/reader_for_microxml>
4. open the current documentation:
<https://docs.rs/crate/reader_for_microxml/1.0.4>
5. open the latest documentation (to see the changes):
<https://docs.rs/crate/reader_for_microxml/1.1.6>

All this commands are simple URL-s. There is no need for any additional data to get or extension behaviour to modify. Very simple.

**Comment by serayuzgur** [comment]
@LucianoBestia  your idea is very nice, I opened a new issue for it.
