### ISSUE TITLE
Local Cargo Index doesn't work when user home directory path has a space

### ISSUE THREAD

**Issue by dljsjr** [serayuzgur/crates#82]
**Describe the bug**
The git command executed by the extension fails (at least on Win10) if there is a space in the user's home directory. It can probably be fixed by surrounding the directory with quotes.

The space in the name causes part of the path to be interpreted as a git subcommand.

**To Reproduce**
1. Create a user with a space in their username on Windows
2. Install VS Code w/ the Crates extension
3. Enable the Use Local Cargo Index feature
4. Open Cargo.toml, all dependencies will have ! next to them. Hovering over it to see the error reveals the issue.

**Expected behavior**
Local index should work even if the user has spaces in their username

**Screenshots**
![image](https://user-images.githubusercontent.com/444635/83275463-cb85d980-a194-11ea-968a-d80376422720.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by serayuzgur** [comment]
Hi, we do not execute any command right now. We just use the available index with folder based path generation. Can you please give further details?

**Comment by SaltErik** [comment]
Can confirm this happens on Win 7 as well -- it's just as @dljsjr describes it.

The problem (AFAIK):
--git-dir=C:\Users\Account Name With Spaces.cargo\etc...

A potential solution:
--git-dir='C:\Users\Account Name With Spaces.cargo\etc...'

Note the quotation marks surrounding the path given to git-dir in the potential solution.

Note also that --git-dir is provided as part of a larger git command.

I assume the git-dir part is the only part that needs this particular fix -- but in practice, any part containing a path should be surrounded in (appropriate) quotes due to whitespace-containing paths being permissible on Windows.

**Comment by dljsjr** [comment]
I think the missing slash before the `.cargo` directory is also an issue as @serayuzgur said but quoting the path also seems to be the problem.

**Comment by serayuzgur** [comment]
I pushed a fix. Can someone please test the master branch ? I don't have Windows to test

**Comment by serayuzgur** [comment]
@dljsjr , @SaltErik ,  can you help? you can use the master branch to build and test

**Comment by dljsjr** [comment]
@serayuzgur I'm unfamiliar with Visual Studio Code extension development, what are the instructions for building and installing the extension from source so I can check this?

**Comment by serayuzgur** [comment]
v5.0.1 will fix this
