### ISSUE TITLE
Show different status indicator for semver-compatible updates

### ISSUE THREAD

**Issue by djc** [serayuzgur/crates#86]
First let me say that I just recently discovered your extension on Twitter and I love it. That said, I think it could be better still, so here's one little suggestion.

**Is your feature request related to a problem? Please describe.**
When reviewing dependency versions I'm usually hunting for semver-incompatible updates, since I use cargo update to bump all the semver-compatible ones. I noticed that your extension already shows 👍 for  versions that are set to "1" for example, but actually it could/should also do this for crates that are set to "1.0.1" for example, since these are semver-compatible cargo will pull in the updates automatically. Setting it to 1.0.1 might be common if you've never tested your crate with 1.0.0 for example, or if you know you need a bugfix from 1.0.1. (Just in case you're not aware, in Cargo.toml "1.0.0" is equivalent to "^1.0.0" rather than  "=1.0.0" -- you probably always want to be show semver-compatible updates in the latter case.)

**Describe the solution you'd like**
Right now your extension either shows 👍 or "Latest: 1.2.3" by default. However, it seems to show "Latest: 1.2.3" even if I have say "1.1.2" configured. It would be nice if it could distinguish between semver-incompatible updates (as in, "2.0") and semver-compatible updates ("1.2.3"). The simplest way to do this could be to show 👍 for semver-compatible updates. A slightly more advanced way could be to distinguish between the case of semver-compatible and the case of semver-incompatible updates (for example, 👍 1.2.3 for semver-compatible and "Latest: 1.2.3" for -incompatible).

**Comment by serayuzgur** [comment]
Hi, thanks for the suggestion. I will think about the idea of semver compatible updates.

**Comment by repi** [comment]
This is one of our few issues with the Crates extension also, we have a lot of crates and a lot of dependencies for our main executable project, and it is an executable we have a `Cargo.lock` file checked in that controls which exact patch version of crates being used. 

So listings by the extensions like this is both redundant but also not correct for us, as the Cargo.lock file determines which patch version we are actually using (which happens to be the same as the latest here).

![image](https://user-images.githubusercontent.com/1262692/90339694-a6b23d00-dff2-11ea-8cb5-2c61233b4693.png)

So the main thing we use the extension for is spotting when there is a major or minor version upgrade which requires manual upgrading. So having them stand out either through coloring or the messaging would be great, or alternatively supporting Cargo.lock files as well

**Comment by fanatid** [comment]
@serayuzgur thank you for a great extension, it's really helpful to see that dependency have a newer version right in the vscode!

I work on [timberio/vector](https://github.com/timberio/vector) and we have a lot of dependencies, a lot of them use the latest version defined in `Cargo.lock`, but in `Cargo.toml` we have the previous version which allows compatible version in `Cargo.lock`, this cause `crates` show that dependency needs to be updated :( This exactly what @repi described.

**Comment by serayuzgur** [comment]
Hi All,
Thanks for the issue. I am working on this right now. I think we should keep this issue at the safe area for now and parsing the lock file is whole new adventure. According to me shipping different semver indicators for the toml file first is best way to take fast action.

**Comment by serayuzgur** [comment]
As I understand  `MAJOR` ,`MINOR ` and `PATCH ` needs to be handled differently and  users need to identify them with a single look of an eye. Since not every one uses `cargo update` and extension can not parse the lock file right now we can't really have "truth" about what version the project uses.  I assume this extension should always show the information about the real situation and showing a lucky guess will might be missleading. 

Here is my idea (waiting for your feedback);

The best I can do right now seems to be showing 3 separate decorators instead of one `Latest XX`information.
Let's say current version is =  0.7.4

And the decorator could be like for ex. `Major:1.0.115   Minor:0.9.15  Patch:0.7.15`  template will be editable as the current settings and users will be free to set whatever he/she wants.  
For ex.
* `Maj: ${major} Min: ${min} P:${patch}`
* `Min: ${min} P:${patch}`
* `P:${patch}`
* `Maj: ${major}`

```
serde = "0.7.4"  (Major:.1.0.115   Minor:0.9.15   Patch:0.7.15)
```

or

```
serde = "0.7.15"  (Major:.1.0.115   Minor:0.9.15   Patch:👍)
```

What do you think?

**Comment by fanatid** [comment]
I like this suggestion! :slightly_smiling_face: 

In the future when `Cargo.lock` parser will be available... if lock file will have `serde = "0.7.15"` next line in `Cargo.toml` will be correct?
```
serde = "0.7.4"  (Major:.1.0.115   Minor:0.9.15   Patch:👍)
```

**Comment by repi** [comment]
Think this may be making it more complicated then it needs be.

Don't think there is a need to show multiple different type of versions, just want to know what is the latest version and  highlight if it  is a major/minor version and make it more subtle if it is a patch version. 

As the patch versions they are generally not something one is manually upgrading and specifying in Cargo.toml (only as a minimum patch version) as Cargo really drives one to use the latest patch version of crates itself (which is great).

So maybe just something simple like:

```
serde = "0.7.4"    Latest patch: 0.7.9

test = "1.1.1"     Latest minor: 1.3.2

test2 = "1.1.1"     Latest major: 2.1.4
```

Ideally with the patch one being more dimmmed/darker/transparent to be less visible than the minor/major updates so they stand out more. That is quite important because think it is very rare both for apps with Cargo.lock and with crates to see that  there is new patch version and update the minimum required patch version in a crate and one o the main ideas is to see the important major/minor updates easily in big Cargo.toml files with lots of  dependencies  which  is currently very hard.

Wouldn't need anything more than this, and keeps the output compact and a good default.

**Comment by serayuzgur** [comment]
@repi  according to your suggestion,
There will be only one decorator for ex `Latest patch: 0.7.9`  or `Latest minor: 1.3.2`
If your version satisfies nothing 
* You will see `Latest patch: 0.7.9`
If your version satisfies
*  PATCH you will see `Latest minor: 1.3.2`
* MINOR you will see `Latest major: 2.1.4`
* MAJOR you will see `👍`

If it is true, I want to call it "Progressive Suggestion"
Am I  right ?

**Comment by repi** [comment]
Sorry I don't fully understand your comment. 

Yes it  will only ever show a single "Latest <which>: <version>" decorator. 

It would compare the current semver in Cargo.toml with the latest available semver of the crate.

If they are identical, show just 👍.

If they do differ, determine if it is the first number in the string (the major version), or the second number (the minor version), or the third number (the patch version) to get which type of new version it is. with the higher semantic versions taking preference (major over minor over patch).

Then display the single `Latest <which>: version` decorator with which upgrade it is and it the appropriate color and the full latest version.

**Comment by djc** [comment]
I think there are three possible states:

* Crate has a semver-incompatible update, thus needs human attention to upgrade -> needs maximum attention
* Crate has a semver-compatible update, thus will automatically be updated by cargo update -> needs minimal attention
* Crate is at the latest version -> needs no attention

Personally I'd appreciate if there was symmetry between all versions, so I'd probably do it like this (if latest is 1.2.3):

```toml
foo = "1.2.3" # (✅)
foo = "1.1" # (👍 latest = 1.2.3)
foo = "0.9" # (⏰ latest = 1.2.3)
```

**Comment by serayuzgur** [comment]
Hello All,
I worked on this issue and  want to share latest status with you. Since it must be  clean but also detailed I did it as combination of what @repi and  @djc suggested.
So I am sharing my S.S. please take a look at and tell me if I got something wrong. Emojis are for the test purpose , they will be editable at preferences.
![Screen Shot 2020-08-31 at 14 54 36](https://user-images.githubusercontent.com/4561330/91717302-eacc4280-eb99-11ea-821d-b57259f46156.png)

**Comment by repi** [comment]
That does look quite good, and I think correct.

Maybe except for this one?

![image](https://user-images.githubusercontent.com/1262692/91717702-4eeb0880-eb92-11ea-9c6c-ebc5784560a9.png)

think that one should be green as version "2" is compatible with the minor update 2.18

**Comment by serayuzgur** [comment]
OK done, it seems that we are ready for the new version. Thanks for all
